name: ROS2 CI

on:
  pull_request:
    branches:
      - 'master'

jobs:
  test_environment:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        ros_distribution:
          - foxy
          - eloquent
        include:
          # Foxy Fitzroy (June 2020 - May 2023)
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-foxy-ros-base-latest
            ros_distribution: foxy
            ros_version: 2

          # Eloquent
          - docker_image: rostooling/setup-ros-docker:ubuntu-focal-ros-eloquent-ros-base-latest
            ros_distribution: eloquent
            ros_version: 2
    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup directories
        run: mkdir -p ros_ws/src
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: ros_ws/src
      - name: build and test
        uses: ros-tooling/action-ros-ci@master
        with:
          import-token: ${{ secrets.REPO_TOKEN }}
          package-name: dummy_pkg
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
